# Generated by Django 4.2.1 on 2023-05-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_type',
            field=models.CharField(choices=[('USER', 'user'), ('CLIENT', 'client')], default='USER', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(choices=[('500_GLOBAL', '500 GLOBAL')], default='500_GLOBAL', max_length=50),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
